const translations = {
  en: {
    // Navigation
    'nav.chat': 'AI Chat',
    'nav.sales': 'Sales Coach',
    'nav.dealer': 'Dealer',
    'nav.enterprise': 'Enterprise',
    'nav.solutions': 'Solutions',
    'nav.news': 'News',
    'nav.learn': 'Learn',
    'nav.market': 'Market',

    // Common
    'common.search': 'Search...',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.export': 'Export',
    'common.copy': 'Copy',
    'common.new': 'New',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',

    // Chat
    'chat.placeholder': 'Ask about products, ROI, compatibility, solutions...',
    'chat.send': 'Send',
    'chat.newChat': 'New Chat',
    'chat.history': 'Chat History',
    'chat.agent': 'Agent',
    'chat.selectAgent': 'Select Agent',
    'chat.thinking': 'Thinking...',
    'chat.source': 'Source',
    'chat.confidence': 'Confidence',
    'chat.copy': 'Copy response',
    'chat.micEn': '🎤 EN',
    'chat.micMr': '🎤 मर',
    'chat.micHi': '🎤 हि',
    'chat.greeting': "Hi! I'm your {name} agent. {description}. How can I help you today?",
    'chat.confidenceSuffix': 'confident',

    // Agents
    'agent.product_intelligence.name': 'Product Intelligence',
    'agent.product_intelligence.description': 'Specs, features, product details',
    'agent.recommendation.name': 'Recommendation',
    'agent.recommendation.description': 'Best products for your needs',
    'agent.compatibility_agent.name': 'Compatibility',
    'agent.compatibility_agent.description': 'Hardware compatibility check',
    'agent.sales_coach.name': 'Sales Coach',
    'agent.sales_coach.description': 'Pitch, objections, negotiation',
    'agent.market_intelligence.name': 'Market Intel',
    'agent.market_intelligence.description': 'Trends, demand, brand data',
    'agent.news_agent.name': 'IT News',
    'agent.news_agent.description': 'Latest IT industry news',
    'agent.forecast_agent.name': 'Forecast',
    'agent.forecast_agent.description': 'Price & demand forecasts',
    'agent.solution_designer.name': 'Solution Designer',
    'agent.solution_designer.description': 'Complete setup design',
    'agent.quotation_agent.name': 'Quotation',
    'agent.quotation_agent.description': 'Generate sales quotations',
    'agent.inventory_agent.name': 'Inventory',
    'agent.inventory_agent.description': 'Stock & availability check',
    'agent.enterprise_agent.name': 'Enterprise',
    'agent.enterprise_agent.description': 'Infra planning, TCO, lifecycle',
    'agent.troubleshoot_agent.name': 'Troubleshoot',
    'agent.troubleshoot_agent.description': 'Diagnose hardware issues',
    'agent.learning_agent.name': 'Learning',
    'agent.learning_agent.description': 'IT hardware education',
    'agent.dealer_agent.name': 'Dealer',
    'agent.dealer_agent.description': 'Schemes, margins, channel',

    // Modules
    'module.chat.title': 'AI Chat — Agent Playground',
    'module.chat.desc': 'Chat with 14 specialized AI agents',
    'module.sales.title': 'Sales Coach Portal',
    'module.sales.desc': 'Playbooks, pitch generator, objection handler',
    'module.dealer.title': 'Dealer Portal',
    'module.dealer.desc': 'Quotations, stock, schemes, margins',
    'module.enterprise.title': 'Enterprise Portal',
    'module.enterprise.desc': 'Infra planning, TCO, lifecycle management',
    'module.solutions.title': 'Solution Designer',
    'module.solutions.desc': 'Design complete IT setups for any use-case',
    'module.news.title': 'IT News Center',
    'module.news.desc': 'Global and India IT news with AI summaries',
    'module.learn.title': 'Learning Center',
    'module.learn.desc': 'Hardware courses, quizzes, certifications',
    'module.market.title': 'Market Intelligence',
    'module.market.desc': 'Demand trends, price forecasts, brand analytics',

    // Sales Coach
    'sales.playbooks': 'Playbooks',
    'sales.pitch': 'Pitch Generator',
    'sales.objection': 'Objection Handler',
    'sales.negotiation': 'Negotiation Coach',
    'sales.discovery': 'Discovery Questions',
    'sales.selectScenario': 'Select Scenario',
    'sales.generatePlaybook': '🚀 Generate Playbook',
    'sales.playbookGenerating': 'Generating...',
    'sales.pitchProduct': 'Product / Solution',
    'sales.pitchCustomer': 'Customer Profile',
    'sales.pitchBudget': 'Budget Range',
    'sales.generatePitch': '✨ Generate Pitch',
    'sales.handleObjection': 'Handle',
    'sales.negotiationTitle': '🤝 Negotiation Coach',
    'sales.negotiationDesc': 'Get AI-powered negotiation strategies specifically for IT hardware deals in the Indian market.',
    'sales.negotiationBtn': '🚀 Get Negotiation Script',
    'sales.discoveryTitle': '🔍 Discovery Questions',
    'sales.discoveryDesc': 'Qualify your prospect with the right questions before making a pitch.',
    'sales.discoveryProduct': 'Product Focus (optional)',
    'sales.discoveryBtn': '🔍 Generate Discovery Questions',

    // Playbook categories
    'sales.playbook.server': 'Server & Storage',
    'sales.playbook.laptop': 'Laptops & Mobile',
    'sales.playbook.network': 'Networking',
    'sales.playbook.printer': 'Print & Scan',

    // Objections
    'sales.objection.price': 'Too expensive',
    'sales.objection.vendor': 'Happy with current vendor',
    'sales.objection.timing': 'Not the right time',
    'sales.objection.specs': 'Need better specs',
    'sales.objection.support': 'Concerned about support',
    'sales.objection.budget': 'Budget not approved',

    // Dealer
    'dealer.quotation': 'Quotation Creator',
    'dealer.stock': 'Stock Checker',
    'dealer.schemes': 'Scheme Board',
    'dealer.bulk': 'Bulk Planner',
    'dealer.margin': 'Margin Calculator',
    'dealer.customerNamePlaceholder': 'Customer / Company name',
    'dealer.productNamePlaceholder': 'Product name',
    'dealer.productHeader': 'Product',
    'dealer.skuHeader': 'SKU',
    'dealer.qtyHeader': 'Qty',
    'dealer.priceHeader': 'Unit Price',
    'dealer.totalHeader': 'Total',
    'dealer.subtotalLabel': 'Subtotal',
    'dealer.gstLabel': 'GST',
    'dealer.grandTotalLabel': 'Grand Total',
    'dealer.copied': '✅ Copied!',
    'dealer.copyQuotation': '📋 Copy Quotation',
    'dealer.addLineItem': '+ Add Line Item',
    'dealer.exportPdf': 'Export PDF',
    'dealer.marginCalculatorTitle': 'Margin Calculator',
    'dealer.sellingPriceLabel': 'Selling Price (MRP)',
    'dealer.costPriceLabel': 'Cost Price',
    'dealer.minQty': 'Min qty',
    'dealer.validTill': 'Valid till',
    'dealer.gstPercent': 'GST %',
    'dealer.quotationPrefix': 'QUOTATION — IT Solutions',
    'dealer.quotationClient': 'Client',
    'dealer.quotationDate': 'Date',

    // Calculator return values
    'Hardware (Year 0)': 'Hardware (Year 0)',
    'Annual operating cost': 'Annual operating cost',
    '{years}-Year TCO': '{years}-Year TCO',
    'Margin %': 'Margin %',
    'Margin ₹': 'Margin ₹',
    'MRP': 'MRP',
    'Cost': 'Cost',

    // Schemes Board
    'HP Spring Surge Q2 2025': 'HP Spring Surge Q2 2025',
    'ProLiant Servers': 'ProLiant Servers',
    'ThinkPad Business Booster': 'ThinkPad Business Booster',
    'ThinkPad Series': 'ThinkPad Series',
    'PowerEdge Partner Promo': 'PowerEdge Partner Promo',
    'PowerEdge + iDRAC': 'PowerEdge + iDRAC',
    'Smart Net Total Care Bundle': 'Smart Net Total Care Bundle',
    'Cisco Switches': 'Cisco Switches',
    'Print More Save More': 'Print More Save More',
    'EcoTank Series': 'EcoTank Series',
    '₹5,000 cashback/unit': '₹5,000 cashback/unit',
    '15% off AMC': '15% off AMC',
    '₹2,000 bundle saving': '₹2,000 bundle saving',
    'Volume': 'Volume',
    'Target': 'Target',
    'Bundle': 'Bundle',
    'Service': 'Service',
    'Ink+Hardware': 'Ink+Hardware',
    'HOT': 'HOT',
    'NEW': 'NEW',
    'LIMITED': 'LIMITED',

    // Enterprise
    'enterprise.infra': 'Infrastructure Planner',
    'enterprise.tco': 'TCO Calculator',
    'enterprise.lifecycle': 'Lifecycle Manager',
    'enterprise.compliance': 'Compliance',
    'enterprise.tcoInputs': '⚙️ TCO Inputs',
    'enterprise.hardwareCost': 'Hardware Cost (₹)',
    'enterprise.maintenanceCost': 'Annual Maintenance (₹)',
    'enterprise.licenseCost': 'Annual License (₹)',
    'enterprise.powerCost': 'Annual Power Cost (₹)',
    'enterprise.period': 'Analysis Period (years)',
    'enterprise.tcoSummary': '📊 TCO Summary',
    'enterprise.yearCumulative': 'Year-by-Year Cumulative',
    'enterprise.year': 'Year',
    'enterprise.customInfraTitle': '🔧 Custom Infrastructure Request',
    'enterprise.customInfraPlaceholder': 'Describe your infrastructure needs...',
    'enterprise.planBtn': 'Plan →',
    'enterprise.planningProgress': 'Designing your infrastructure plan...',
    'enterprise.smbOffice': 'SMB Office (25 users)',
    'enterprise.smbOfficeDesc': 'Complete setup for small business',
    'enterprise.entOffice': 'Enterprise (200 users)',
    'enterprise.entOfficeDesc': 'Full data center + end-user compute',
    'enterprise.hospital': 'Hospital / Healthcare',
    'enterprise.hospitalDesc': 'HIPAA-compliant setup',
    'enterprise.school': 'School / Education',
    'enterprise.schoolDesc': 'Cost-effective learning environment',

    // Market
    'market.demand': 'Demand Index',
    'market.price': 'Price Trends',
    'market.forecast': 'Forecasts',
    'market.brands': 'Brand Share',
    'market.disclaimer': '⚠️ Forecasts are AI estimates — not guaranteed',
    'market.loading': 'Loading market charts and analytics...',
    'market.demandIndexTitle': 'Demand Index (Last 6 Months)',
    'market.priceTrendTitle': 'Price Trend (History + Dotted AI Forecast)',
    'market.brandShareTitle': 'Brand Market Share (Regional Distribution)',
    'market.seasonalPatternTitle': 'Seasonal Demand Pattern',
    'market.peakWindowTag': 'Next Peak Seasonal Window',
    'market.peakWindowDesc': 'July - August: Higher Education Admissions Refresh Cycle',
    'market.forecastTitle': 'AI Market Intelligence Forecast (Next 90 Days)',
    'market.disclaimerTag': 'DISCLAIMER',
    'market.chart.history': 'History',
    'market.chart.forecast': 'AI Forecast',
    'market.chart.prev': 'Prev',
    'market.chart.current': 'Current',
    'market.month.Jan': 'Jan',
    'market.month.Feb': 'Feb',
    'market.month.Mar': 'Mar',
    'market.month.Apr': 'Apr',
    'market.month.May': 'May',
    'market.month.Jun': 'Jun',

    // News
    'news.allNews': 'All News',
    'news.globalIt': 'Global IT',
    'news.indiaIt': 'India IT',
    'news.brandNews': 'Brand News',
    'news.launches': 'Launches',
    'news.aiHardware': 'AI Hardware',
    'news.semiconductors': 'Semiconductors',
    'news.supplyChain': 'Supply Chain',
    'news.trends': 'Trends',
    'news.govtPolicy': 'Govt. Policy',
    'news.searchPlaceholder': 'Search news...',
    'news.loading': 'Loading IT news articles...',
    'news.noNews': 'No news articles found in this category matching your search.',
    'news.businessImpactTitle': '💼 Business Impact (Dealers)',
    'news.technicalImpactTitle': '⚙️ Technical Impact (Specifications)',
    'news.relatedProducts': 'Related Products: ',
    'news.readLess': 'Read Less ▲',
    'news.readMore': 'Analyze Business Impact ▼',
    'news.askAi': 'Ask AI Assistant 🤖',

    // Learn
    'learn.certificationsEarned': 'Certifications Earned:',
    'learn.knowledgeModules': 'Knowledge Modules',
    'learn.topic': 'Module Topic:',
    'learn.readLesson': 'Read Lesson',
    'learn.takeQuiz': 'Take Quiz',
    'learn.readyText': 'Ready to test your knowledge?',
    'learn.readyDesc': 'Complete the 5-question quiz. Score 80% (4 correct answers) to earn your certification badge.',
    'learn.startQuiz': 'Start Interactive Quiz ✍️',
    'learn.submitAnswers': 'Submit Answers',
    'learn.certEarned': '🏆 Certification Earned!',
    'learn.tryAgain': '😢 Try Again',
    'learn.scoreText': 'You scored {score}% ({correct} / {total} correct answers).',
    'learn.retakeQuiz': 'Retake Quiz',
    'learn.selectModule': 'Select a Module to Start Learning',
    'learn.selectModuleDesc': 'Choose a hardware or network category from the left pane to view tutorials, test your skills, and earn official certifications.',
    'learn.explanation': 'Explanation:',

    // Solutions
    'solutions.selectUseCase': '1. Select Use Case',
    'solutions.scaleBudget': '2. Scale & Budget',
    'solutions.priorities': '3. Priorities',
    'solutions.userCount': 'Number of Users',
    'solutions.budgedRange': 'Budget Range',
    'solutions.designBtn': '⚡ Design My Solution',
    'solutions.designProgress': '⚡ Designing Solution...',
    'solutions.configureGenerate': 'Configure & Generate',
    'solutions.configureGenerateDesc': 'Select a use case, set your scale and budget, then click Design My Solution for a complete IT setup recommendation.',
    'solutions.designingMessage': 'Designing your custom IT solution...',
    'solutions.customPlaceholder': 'Or describe your custom use case...',
    'solutions.titleOutput': 'Solution Design',
    'solutions.copyBtn': '📋 Copy',

    // Budget ranges
    'Under ₹2 Lakh': 'Under ₹2 Lakh',
    '₹2–5 Lakh': '₹2–5 Lakh',
    '₹5–15 Lakh': '₹5–15 Lakh',
    '₹15–50 Lakh': '₹15–50 Lakh',
    'Above ₹50 Lakh': 'Above ₹50 Lakh',

    // Use cases & priority
    'solutions.usecase.office': 'Office Setup',
    'solutions.usecase.video': 'Video Production',
    'solutions.usecase.retail': 'Retail/POS',
    'solutions.usecase.datacenter': 'Mini Data Center',
    'solutions.usecase.creative': 'Creative Agency',
    'solutions.usecase.hospital': 'Clinic / Hospital',
    'solutions.usecase.school': 'School Lab',
    'solutions.usecase.warehouse': 'Warehouse / Logistics',
    'solutions.priority.performance': 'Performance',
    'solutions.priority.cost': 'Cost-effective',
    'solutions.priority.energy': 'Energy efficient',
    'solutions.priority.scalable': 'Scalable',
    'solutions.priority.manage': 'Easy to manage',
    'solutions.priority.availability': 'High availability',

    // Language names
    'lang.en': 'EN',
    'lang.mr': 'मर',
    'lang.hi': 'हि',
  },
  mr: {
    // Navigation
    'nav.chat': 'AI चॅट',
    'nav.sales': 'सेल्स कोच',
    'nav.dealer': 'डीलर',
    'nav.enterprise': 'एंटरप्राइज',
    'nav.solutions': 'सोल्युशन',
    'nav.news': 'बातम्या',
    'nav.learn': 'शिका',
    'nav.market': 'बाजार',

    // Common
    'common.search': 'शोधा...',
    'common.loading': 'लोड होत आहे...',
    'common.error': 'त्रुटी',
    'common.retry': 'पुन्हा प्रयत्न करा',
    'common.close': 'बंद करा',
    'common.back': 'मागे',
    'common.save': 'जतन करा',
    'common.export': 'निर्यात',
    'common.copy': 'कॉपी करा',
    'common.new': 'नवीन',
    'common.delete': 'हटवा',
    'common.edit': 'संपादन',
    'common.view': 'पाहा',
    'common.submit': 'सादर करा',
    'common.cancel': 'रद्द करा',

    // Chat
    'chat.placeholder': 'उत्पादने, ROI, सुसंगतता, सोल्युशन विचारा...',
    'chat.send': 'पाठवा',
    'chat.newChat': 'नवीन चॅट',
    'chat.history': 'चॅट इतिहास',
    'chat.agent': 'एजंट',
    'chat.selectAgent': 'एजंट निवडा',
    'chat.thinking': 'विचार करत आहे...',
    'chat.source': 'स्रोत',
    'chat.confidence': 'विश्वास',
    'chat.copy': 'प्रतिसाद कॉपी करा',
    'chat.micEn': '🎤 EN',
    'chat.micMr': '🎤 मर',
    'chat.micHi': '🎤 हि',
    'chat.greeting': "नमस्कार! मी तुमचा {name} एजंट आहे. {description}. मी आज तुम्हाला कशी मदत करू शकतो?",
    'chat.confidenceSuffix': 'विश्वासू',

    // Agents
    'agent.product_intelligence.name': 'उत्पादन माहिती',
    'agent.product_intelligence.description': 'स्पेक्स, वैशिष्ट्ये, उत्पादन तपशील',
    'agent.recommendation.name': 'शिफारस एजंट',
    'agent.recommendation.description': 'तुमच्या गरजांसाठी सर्वोत्तम उत्पादने',
    'agent.compatibility_agent.name': 'सुसंगतता एजंट',
    'agent.compatibility_agent.description': 'हार्डवेअर सुसंगतता तपासा',
    'agent.sales_coach.name': 'सेल्स कोच',
    'agent.sales_coach.description': 'पिच, आक्षेप, वाटाघाटी',
    'agent.market_intelligence.name': 'मार्केट इंटेलिजन्स',
    'agent.market_intelligence.description': 'ट्रेंड्स, मागणी, ब्रँड डेटा',
    'agent.news_agent.name': 'आयटी न्यूज',
    'agent.news_agent.description': 'नवीनतम आयटी उद्योग बातम्या',
    'agent.forecast_agent.name': 'पूर्वानुमान एजंट',
    'agent.forecast_agent.description': 'किंमत आणि मागणीचे अंदाज',
    'agent.solution_designer.name': 'सोल्युशन डिझायनर',
    'agent.solution_designer.description': 'पूर्ण सेटअप डिझाइन',
    'agent.quotation_agent.name': 'कोटेशन एजंट',
    'agent.quotation_agent.description': 'विक्रीचे कोटेशन जनरेट करा',
    'agent.inventory_agent.name': 'इन्व्हेंटरी एजंट',
    'agent.inventory_agent.description': 'स्टॉक आणि उपलब्धता तपासा',
    'agent.enterprise_agent.name': 'एंटरप्राइज एजंट',
    'agent.enterprise_agent.description': 'इन्फ्रा नियोजन, TCO, जीवनचक्र',
    'agent.troubleshoot_agent.name': 'निवारण एजंट',
    'agent.troubleshoot_agent.description': 'हार्डवेअर समस्यांचे निदान करा',
    'agent.learning_agent.name': 'शिक्षण एजंट',
    'agent.learning_agent.description': 'IT हार्डवेअर शिक्षण',
    'agent.dealer_agent.name': 'डीलर एजंट',
    'agent.dealer_agent.description': 'योजना, मार्जिन, चॅनेल',

    // Modules
    'module.chat.title': 'AI चॅट — एजंट प्लेग्राउंड',
    'module.chat.desc': '१४ विशेष AI एजंटशी चॅट करा',
    'module.sales.title': 'सेल्स कोच पोर्टल',
    'module.sales.desc': 'प्लेबुक, पिच जनरेटर, आक्षेप हँडलर',
    'module.dealer.title': 'डीलर पोर्टल',
    'module.dealer.desc': 'कोटेशन, स्टॉक, योजना, मार्जिन',
    'module.enterprise.title': 'एंटरप्राइज पोर्टल',
    'module.enterprise.desc': 'इन्फ्रा नियोजन, TCO, जीवनचक्र व्यवस्थापन',
    'module.solutions.title': 'सोल्युशन डिझायनर',
    'module.solutions.desc': 'कोणत्याही वापरासाठी IT सेटअप डिझाइन करा',
    'module.news.title': 'IT बातम्या केंद्र',
    'module.news.desc': 'जागतिक आणि भारतीय IT बातम्या AI सारांशासह',
    'module.learn.title': 'शिक्षण केंद्र',
    'module.learn.desc': 'हार्डवेअर अभ्यासक्रम, प्रश्नमंजुषा, प्रमाणपत्रे',
    'module.market.title': 'बाजार बुद्धिमत्ता',
    'module.market.desc': 'मागणी ट्रेंड, किंमत अंदाज, ब्रँड विश्लेषण',

    // Sales Coach
    'sales.playbooks': 'प्लेबुक',
    'sales.pitch': 'पिच जनरेटर',
    'sales.objection': 'आक्षेप हँडलर',
    'sales.negotiation': 'वाटाघाट कोच',
    'sales.discovery': 'शोध प्रश्न',
    'sales.selectScenario': 'प्रसंग निवडा',
    'sales.generatePlaybook': '🚀 प्लेबुक जनरेट करा',
    'sales.playbookGenerating': 'जनरेट करत आहे...',
    'sales.pitchProduct': 'उत्पादन / सोल्युशन',
    'sales.pitchCustomer': 'ग्राहक प्रोफाइल',
    'sales.pitchBudget': 'बजेट श्रेणी',
    'sales.generatePitch': '✨ पिच जनरेट करा',
    'sales.handleObjection': 'हाताळा',
    'sales.negotiationTitle': '🤝 वाटाघाटी मार्गदर्शक',
    'sales.negotiationDesc': 'भारतीय बाजारपेठेतील आयटी हार्डवेअर करारांसाठी AI-आधारित वाटाघाटी धोरणे मिळवा.',
    'sales.negotiationBtn': '🚀 वाटाघाटी स्क्रिप्ट मिळवा',
    'sales.discoveryTitle': '🔍 शोध प्रश्न',
    'sales.discoveryDesc': 'पिच देण्यापूर्वी तुमच्या ग्राहकाची पात्रता तपासा.',
    'sales.discoveryProduct': 'उत्पादन फोकस (पर्यायी)',
    'sales.discoveryBtn': '🔍 शोध प्रश्न जनरेट करा',

    // Playbook categories
    'sales.playbook.server': 'सर्व्हर आणि स्टोरेज',
    'sales.playbook.laptop': 'लॅपटॉप आणि मोबाईल',
    'sales.playbook.network': 'नेटवर्किंग',
    'sales.playbook.printer': 'प्रिंट आणि स्कॅन',

    // Objections
    'sales.objection.price': 'खूप महाग आहे',
    'sales.objection.vendor': 'सध्याच्या विक्रेत्यासोबत समाधानी आहे',
    'sales.objection.timing': 'योग्य वेळ नाही',
    'sales.objection.specs': 'अधिक चांगल्या स्पेसिफिकेशनची आवश्यकता आहे',
    'sales.objection.support': 'सपोर्टबद्दल चिंता आहे',
    'sales.objection.budget': 'बजेट मंजूर झाले नाही',

    // Dealer
    'dealer.quotation': 'कोटेशन',
    'dealer.stock': 'स्टॉक तपासा',
    'dealer.schemes': 'योजना बोर्ड',
    'dealer.bulk': 'बल्क प्लानर',
    'dealer.margin': 'मार्जिन कॅल्क्युलेटर',
    'dealer.customerNamePlaceholder': 'ग्राहक / कंपनीचे नाव',
    'dealer.productNamePlaceholder': 'उत्पादनाचे नाव',
    'dealer.productHeader': 'उत्पादन',
    'dealer.skuHeader': 'SKU',
    'dealer.qtyHeader': 'प्रमाण',
    'dealer.priceHeader': 'दर',
    'dealer.totalHeader': 'एकूण',
    'dealer.subtotalLabel': 'उपएकूण',
    'dealer.gstLabel': 'जीएसटी',
    'dealer.grandTotalLabel': 'एकूण देय रक्कम',
    'dealer.copied': '✅ कॉपी केले!',
    'dealer.copyQuotation': '📋 कोटेशन कॉपी करा',
    'dealer.addLineItem': '+ नवीन ओळ जोडा',
    'dealer.exportPdf': 'पीडीएफ डाउनलोड करा',
    'dealer.marginCalculatorTitle': 'मार्जिन कॅल्क्युलेटर',
    'dealer.sellingPriceLabel': 'विक्री किंमत (MRP)',
    'dealer.costPriceLabel': 'खरेदी किंमत',
    'dealer.minQty': 'किमान प्रमाण',
    'dealer.validTill': 'वैधता तारीख',
    'dealer.gstPercent': 'जीएसटी %',
    'dealer.quotationPrefix': 'कोटेशन — IT सोल्यूशन्स',
    'dealer.quotationClient': 'ग्राहक',
    'dealer.quotationDate': 'दिनांक',

    // Calculator return values
    'Hardware (Year 0)': 'हार्डवेअर (वर्ष ०)',
    'Annual operating cost': 'वार्षिक चालू खर्च',
    '{years}-Year TCO': '{years}-वर्ष TCO',
    'Margin %': 'मार्जिन %',
    'Margin ₹': 'मार्जिन ₹',
    'MRP': 'विक्री किंमत (MRP)',
    'Cost': 'खरेदी किंमत',

    // Schemes Board
    'HP Spring Surge Q2 2025': 'एचपी स्प्रिंग सर्ज Q२ २०२५',
    'ProLiant Servers': 'प्रोलायंट सर्व्हर्स',
    'ThinkPad Business Booster': 'थिंकपॅड बिझनेस बूस्टर',
    'ThinkPad Series': 'थिंकपॅड सिरीज',
    'PowerEdge Partner Promo': 'पॉवरएज पार्टनर प्रोमो',
    'PowerEdge + iDRAC': 'पॉवरएज + iDRAC',
    'Smart Net Total Care Bundle': 'स्मार्ट नेट Total Care बंडल',
    'Cisco Switches': 'सिस्को स्विचेस',
    'Print More Save More': 'प्रिंट मोअर सेव्ह मोअर',
    'EcoTank Series': 'इकोटँक सिरीज',
    '₹5,000 cashback/unit': '₹५,००० कॅशबॅक/युनिट',
    '15% off AMC': 'एएमसी वर १५% सूट',
    '₹2,000 bundle saving': '₹२,००० बंडल बचत',
    'Volume': 'व्हॉल्यूम',
    'Target': 'टार्गेट',
    'Bundle': 'बंडल',
    'Service': 'सेवा',
    'Ink+Hardware': 'इंक+हार्डवेअर',
    'HOT': 'प्रसिद्ध',
    'NEW': 'नवीन',
    'LIMITED': 'मर्यादित',

    // Enterprise
    'enterprise.infra': 'इन्फ्रा नियोजक',
    'enterprise.tco': 'TCO कॅल्क्युलेटर',
    'enterprise.lifecycle': 'जीवनचक्र व्यवस्थापक',
    'enterprise.compliance': 'अनुपालन',
    'enterprise.tcoInputs': '⚙️ TCO इनपुट',
    'enterprise.hardwareCost': 'हार्डवेअर किंमत (₹)',
    'enterprise.maintenanceCost': 'वार्षिक देखभाल (₹)',
    'enterprise.licenseCost': 'वार्षिक परवाना (₹)',
    'enterprise.powerCost': 'वार्षिक वीज खर्च (₹)',
    'enterprise.period': 'विश्लेषण कालावधी (वर्षे)',
    'enterprise.tcoSummary': '📊 TCO सारांश',
    'enterprise.yearCumulative': 'दरवर्षी संचित',
    'enterprise.year': 'वर्ष',
    'enterprise.customInfraTitle': '🔧 सानुकूल इन्फ्रा विनंती',
    'enterprise.customInfraPlaceholder': 'तुमच्या इन्फ्रास्ट्रक्चरच्या गरजांचे वर्णन करा...',
    'enterprise.planBtn': 'नियोजन →',
    'enterprise.planningProgress': 'तुमची इन्फ्रास्ट्रक्चर योजना डिझाइन करत आहे...',
    'enterprise.smbOffice': 'SMB ऑफिस (२५ युजर्स)',
    'enterprise.smbOfficeDesc': 'लहान व्यवसायासाठी पूर्ण सेटअप',
    'enterprise.entOffice': 'एंटरप्राइज (२०० युजर्स)',
    'enterprise.entOfficeDesc': 'पूर्ण डेटा सेंटर + एंड-युजर कॉम्प्युट',
    'enterprise.hospital': 'हॉस्पिटल / हेल्थकेअर',
    'enterprise.hospitalDesc': 'HIPAA-सुसंगत सेटअप',
    'enterprise.school': 'शाळा / शिक्षण',
    'enterprise.schoolDesc': 'किफायतशीर शैक्षणिक वातावरण',

    // Market
    'market.demand': 'मागणी निर्देशांक',
    'market.price': 'किंमत ट्रेंड',
    'market.forecast': 'अंदाज',
    'market.brands': 'ब्रँड हिस्सा',
    'market.disclaimer': '⚠️ अंदाज AI अनुमान आहेत — हमी नाही',
    'market.loading': 'मार्केट चार्ट आणि विश्लेषण लोड होत आहे...',
    'market.demandIndexTitle': 'मागणी निर्देशांक (गेले ६ महिने)',
    'market.priceTrendTitle': 'किंमत ट्रेंड (इतिहास + डॉटेड AI अंदाज)',
    'market.brandShareTitle': 'ब्रँड मार्केट शेअर (प्रादेशिक वितरण)',
    'market.seasonalPatternTitle': 'हंगामी मागणी पॅटर्न',
    'market.peakWindowTag': 'पुढील पीक सीझनल विंडो',
    'market.peakWindowDesc': 'जुलै - ऑगस्ट: उच्च शिक्षण प्रवेश रिफ्रेश सायकल',
    'market.forecastTitle': 'AI मार्केट इंटेलिजन्स अंदाज (पुढील ९० दिवस)',
    'market.disclaimerTag': 'अस्वीकरण',
    'market.chart.history': 'इतिहास',
    'market.chart.forecast': 'AI अंदाज',
    'market.chart.prev': 'मागील',
    'market.chart.current': 'चालू',
    'market.month.Jan': 'जाने',
    'market.month.Feb': 'फेब्रु',
    'market.month.Mar': 'मार्च',
    'market.month.Apr': 'एप्रिल',
    'market.month.May': 'मे',
    'market.month.Jun': 'जून',

    // News
    'news.allNews': 'सर्व बातम्या',
    'news.globalIt': 'जागतिक IT',
    'news.indiaIt': 'भारतीय IT',
    'news.brandNews': 'ब्रँड बातम्या',
    'news.launches': 'लाँचिंग',
    'news.aiHardware': 'AI हार्डवेअर',
    'news.semiconductors': 'सेमीकंडक्टर',
    'news.supplyChain': 'सप्लाय चेन',
    'news.trends': 'ट्रेंड्स',
    'news.govtPolicy': 'शासकीय धोरण',
    'news.searchPlaceholder': 'बातम्या शोधा...',
    'news.loading': 'IT बातम्या लोड होत आहेत...',
    'news.noNews': 'या श्रेणीमध्ये तुमच्या शोधाशी जुळणारी बातमी सापडली नाही.',
    'news.businessImpactTitle': '💼 व्यावसायिक प्रभाव (डीलर)',
    'news.technicalImpactTitle': '⚙️ तांत्रिक प्रभाव (स्पेसिफिकेशन्स)',
    'news.relatedProducts': 'संबंधित उत्पादने: ',
    'news.readLess': 'कमी वाचा ▲',
    'news.readMore': 'व्यावसायिक प्रभाव विश्लेषण ▼',
    'news.askAi': 'AI असिस्टंटला विचारा 🤖',

    // Learn
    'learn.certificationsEarned': 'मिळवलेली प्रमाणपत्रे:',
    'learn.knowledgeModules': 'ज्ञान मॉड्युल्स',
    'learn.topic': 'मॉड्यूल विषय:',
    'learn.readLesson': 'धडा वाचा',
    'learn.takeQuiz': 'प्रश्नमंजुषा द्या',
    'learn.readyText': 'ज्ञानाची चाचणी घेण्यासाठी तयार आहात का?',
    'learn.readyDesc': '५ प्रश्नांची प्रश्नमंजुषा पूर्ण करा. प्रमाणपत्र बॅज मिळवण्यासाठी ८०% (४ अचूक उत्तरे) गुण मिळवा.',
    'learn.startQuiz': 'इंटरएक्टिव्ह प्रश्नमंजुषा सुरू करा ✍️',
    'learn.submitAnswers': 'उत्तरे सादर करा',
    'learn.certEarned': '🏆 प्रमाणपत्र मिळाले!',
    'learn.tryAgain': '😢 पुन्हा प्रयत्न करा',
    'learn.scoreText': 'तुम्ही {score}% मिळवले ({correct} / {total} अचूक उत्तरे).',
    'learn.retakeQuiz': 'प्रश्नमंजुषा पुन्हा द्या',
    'learn.selectModule': 'शिकणे सुरू करण्यासाठी एक मॉड्यूल निवडा',
    'learn.selectModuleDesc': 'ट्यूटोरियल पाहण्यासाठी, कौशल्यांची चाचणी घेण्यासाठी आणि अधिकृत प्रमाणपत्रे मिळवण्यासाठी डावीकडील यादीतून एक पर्याय निवडा.',
    'learn.explanation': 'स्पष्टीकरण:',

    // Solutions
    'solutions.selectUseCase': '१. वापराचा प्रकार निवडा',
    'solutions.scaleBudget': '२. स्केल आणि बजेट',
    'solutions.priorities': '३. प्राधान्यक्रम',
    'solutions.userCount': 'युजर्सची संख्या',
    'solutions.budgedRange': 'बजेट श्रेणी',
    'solutions.designBtn': '⚡ माझे सोल्युशन डिझाइन करा',
    'solutions.designProgress': '⚡ सोल्युशन डिझाइन करत आहे...',
    'solutions.configureGenerate': 'कॉन्फिगर आणि जनरेट',
    'solutions.configureGenerateDesc': 'वापराचा प्रकार निवडा, स्केल आणि बजेट सेट करा आणि शिफारसींसाठी "माझे सोल्युशन डिझाइन करा" वर क्लिक करा.',
    'solutions.designingMessage': 'तुमचे सानुकूल IT सोल्युशन डिझाइन करत आहे...',
    'solutions.customPlaceholder': 'किंवा सानुकूल वापराचे वर्णन करा...',
    'solutions.titleOutput': 'सोल्युशन डिझाइन',
    'solutions.copyBtn': '📋 कॉपी',

    // Budget ranges
    'Under ₹2 Lakh': '₹२ लाखांपेक्षा कमी',
    '₹2–5 Lakh': '₹२–५ लाख',
    '₹5–15 Lakh': '₹५–१५ लाख',
    '₹15–50 Lakh': '₹१५–५० लाख',
    'Above ₹50 Lakh': '₹५० लाखांपेक्षा जास्त',

    // Use cases & priority
    'solutions.usecase.office': 'ऑफिस सेटअप',
    'solutions.usecase.video': 'व्हिडिओ प्रोडक्शन',
    'solutions.usecase.retail': 'रिटेल/POS सेटअप',
    'solutions.usecase.datacenter': 'मिनी डेटा सेंटर',
    'solutions.usecase.creative': 'क्रिएटिव्ह एजन्सी',
    'solutions.usecase.hospital': 'क्लिनिक / हॉस्पिटल',
    'solutions.usecase.school': 'शाळा लॅब',
    'solutions.usecase.warehouse': 'वेअरहाऊस / लॉजिस्टिक',
    'solutions.priority.performance': 'उत्कृष्ट कामगिरी',
    'solutions.priority.cost': 'किफायतशीर',
    'solutions.priority.energy': 'ऊर्जा कार्यक्षम',
    'solutions.priority.scalable': 'स्केलेबल',
    'solutions.priority.manage': 'व्यवस्थापनास सुलभ',
    'solutions.priority.availability': 'उच्च उपलब्धता',

    // Language names
    'lang.en': 'EN',
    'lang.mr': 'मर',
    'lang.hi': 'हि',
  },
  hi: {
    // Navigation
    'nav.chat': 'AI चैट',
    'nav.sales': 'सेल्स कोच',
    'nav.dealer': 'डीलर',
    'nav.enterprise': 'एंटरप्राइज',
    'nav.solutions': 'सॉल्यूशन',
    'nav.news': 'समाचार',
    'nav.learn': 'सीखें',
    'nav.market': 'बाज़ार',

    // Common
    'common.search': 'खोजें...',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.retry': 'पुनः प्रयास',
    'common.close': 'बंद करें',
    'common.back': 'वापस',
    'common.save': 'सहेजें',
    'common.export': 'निर्यात',
    'common.copy': 'कॉपी करें',
    'common.new': 'नया',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित',
    'common.view': 'देखें',
    'common.submit': 'सबमिट',
    'common.cancel': 'रद्द करें',

    // Chat
    'chat.placeholder': 'उत्पाद, ROI, संगतता, सॉल्यूशन पूछें...',
    'chat.send': 'भेजें',
    'chat.newChat': 'नई चैट',
    'chat.history': 'कन्वर्सेशन',
    'chat.agent': 'एजेंट',
    'chat.selectAgent': 'एजेंट चुनें',
    'chat.thinking': 'सोच रहा है...',
    'chat.source': 'स्रोत',
    'chat.confidence': 'विश्वास',
    'chat.copy': 'उत्तर कॉपी करें',
    'chat.micEn': '🎤 EN',
    'chat.micMr': '🎤 मर',
    'chat.micHi': '🎤 हि',
    'chat.greeting': "नमस्कार! मैं आपका {name} एजेंट हूँ. {description}. मैं आज आपकी क्या सहायता कर सकता हूँ?",
    'chat.confidenceSuffix': 'विश्वस्त',

    // Agents
    'agent.product_intelligence.name': 'उत्पाद विशेषज्ञ',
    'agent.product_intelligence.description': 'स्पेक्स, विशेषताएं, उत्पाद विवरण',
    'agent.recommendation.name': 'सिफारिश सहायक',
    'agent.recommendation.description': 'आपकी आवश्यकताओं के लिए सर्वोत्तम उत्पाद',
    'agent.compatibility_agent.name': 'संगतता जांच',
    'agent.compatibility_agent.description': 'हार्डवेयर संगतता जांचें',
    'agent.sales_coach.name': 'सेल्स कोच',
    'agent.sales_coach.description': 'पिच, आपत्तियां, बातचीत',
    'agent.market_intelligence.name': 'बाज़ार इंटेल',
    'agent.market_intelligence.description': 'रुझान, मांग, ब्रांड डेटा',
    'agent.news_agent.name': 'आईटी न्यूज',
    'agent.news_agent.description': 'आईटी उद्योग के नवीनतम समाचार',
    'agent.forecast_agent.name': 'पूर्वानुमान',
    'agent.forecast_agent.description': 'मूल्य और मांग के पूर्वानुमान',
    'agent.solution_designer.name': 'सॉल्यूशन डिज़ाइनर',
    'agent.solution_designer.description': 'पूर्ण सेटअप डिज़ाइन',
    'agent.quotation_agent.name': 'कोटेशन',
    'agent.quotation_agent.description': 'बिक्री कोटेशन जनरेट करें',
    'agent.inventory_agent.name': 'इन्वेंटरी',
    'agent.inventory_agent.description': 'स्टॉक और उपलब्धता की जांच',
    'agent.enterprise_agent.name': 'एंटरप्राइज',
    'agent.enterprise_agent.description': 'इन्फ्रा नियोजन, TCO, जीवनचक्र',
    'agent.troubleshoot_agent.name': 'समस्या निवारण',
    'agent.troubleshoot_agent.description': 'हार्डवेयर समस्याओं का निदान',
    'agent.learning_agent.name': 'सीखने का माध्यम',
    'agent.learning_agent.description': 'IT हार्डवेयर शिक्षा',
    'agent.dealer_agent.name': 'डीलर',
    'agent.dealer_agent.description': 'स्कीम, मार्जिन, चैनल',

    // Modules
    'module.chat.title': 'AI चैट — एजेंट प्लेग्राउंड',
    'module.chat.desc': '14 विशेष AI एजेंटों से चैट करें',
    'module.sales.title': 'सेल्स कोच पोर्टल',
    'module.sales.desc': 'playbooks, पिच जनरेटर, आपत्ति हैंडलर',
    'module.dealer.title': 'डीलर पोर्टल',
    'module.dealer.desc': 'कोटेशन, स्टॉक, स्कीम, मार्जिन',
    'module.enterprise.title': 'एंटरप्राइज पोर्टल',
    'module.enterprise.desc': 'इन्फ्रा नियोजन, TCO, जीवनचक्र प्रबंधन',
    'module.solutions.title': 'सॉल्यूशन डिज़ाइनर',
    'module.solutions.desc': 'किसी भी उपयोग के लिए IT सेटअप डिज़ाइन करें',
    'module.news.title': 'IT समाचार केंद्र',
    'module.news.desc': 'वैश्विक और भारतीय IT समाचार AI सारांश के साथ',
    'module.learn.title': 'सीखने का केंद्र',
    'module.learn.desc': 'हार्डवेयर कोर्स, क्विज़, प्रमाणपत्र',
    'module.market.title': 'बाज़ार बुद्धिमत्ता',
    'module.market.desc': 'मांग रुझान, मूल्य पूर्वानुमान, ब्रांड विश्लेषण',

    // Sales Coach
    'sales.playbooks': 'प्लेबुक',
    'sales.pitch': 'पिच जेनरेटर',
    'sales.objection': 'आपत्ति हैंडलर',
    'sales.negotiation': 'बातचीत कोच',
    'sales.discovery': 'डिस्कवरी प्रश्न',
    'sales.selectScenario': 'परिदृश्य चुनें',
    'sales.generatePlaybook': '🚀 प्लेबुक जेनरेट करें',
    'sales.playbookGenerating': 'जनरेट हो रहा है...',
    'sales.pitchProduct': 'उत्पाद / सॉल्यूशन',
    'sales.pitchCustomer': 'ग्राहक प्रोफ़ाइल',
    'sales.pitchBudget': 'बजेट रेंज',
    'sales.generatePitch': '✨ पिच जेनरेट करें',
    'sales.handleObjection': 'संभालें',
    'sales.negotiationTitle': '🤝 बातचीत कोच',
    'sales.negotiationDesc': 'भारतीय बाजार में आईटी हार्डवेयर सौदों के लिए AI-आधारित बातचीत रणनीतियां प्राप्त करें.',
    'sales.negotiationBtn': '🚀 बातचीत स्क्रिप्ट प्राप्त करें',
    'sales.discoveryTitle': '🔍 डिस्कवरी प्रश्न',
    'sales.discoveryDesc': 'पिच तैयार करने से पहले अपने ग्राहक की आवश्यकताओं को सही तरीके से समझें.',
    'sales.discoveryProduct': 'उत्पाद फोकस (वैकल्पिक)',
    'sales.discoveryBtn': '🔍 डिस्कवरी प्रश्न जेनरेट करें',

    // Playbook categories
    'sales.playbook.server': 'सर्वर और स्टोरेज',
    'sales.playbook.laptop': 'लैपटॉप और मोबाइल',
    'sales.playbook.network': 'नेटवर्किंग',
    'sales.playbook.printer': 'प्रिंट और स्कैन',

    // Objections
    'sales.objection.price': 'बहुत महंगा है',
    'sales.objection.vendor': 'वर्तमान विक्रेता से खुश हूँ',
    'sales.objection.timing': 'सही समय नहीं है',
    'sales.objection.specs': 'बेहतर स्पेसिफिकेशन की जरूरत है',
    'sales.objection.support': 'सपोर्ट को लेकर चिंतित हूँ',
    'sales.objection.budget': 'बजट स्वीकृत नहीं हुआ',

    // Dealer
    'dealer.quotation': 'कोटेशन',
    'dealer.stock': 'स्टॉक जांचें',
    'dealer.schemes': 'स्कीम बोर्ड',
    'dealer.bulk': 'बल्क प्लानर',
    'dealer.margin': 'मार्जिन कैलकुलेटर',
    'dealer.customerNamePlaceholder': 'ग्राहक / कंपनी का नाम',
    'dealer.productNamePlaceholder': 'उत्पाद का नाम',
    'dealer.productHeader': 'उत्पाद',
    'dealer.skuHeader': 'SKU',
    'dealer.qtyHeader': 'मात्रा',
    'dealer.priceHeader': 'दर',
    'dealer.totalHeader': 'कुल',
    'dealer.subtotalLabel': 'उप-योग',
    'dealer.gstLabel': 'जीएसटी',
    'dealer.grandTotalLabel': 'कुल देय राशि',
    'dealer.copied': '✅ कॉपी हो गया!',
    'dealer.copyQuotation': '📋 कोटेशन कॉपी करें',
    'dealer.addLineItem': '+ नई पंक्ति जोड़ें',
    'dealer.exportPdf': 'पीडीएफ निर्यात करें',
    'dealer.marginCalculatorTitle': 'मार्जिन कैलकुलेटर',
    'dealer.sellingPriceLabel': 'बिक्री मूल्य (MRP)',
    'dealer.costPriceLabel': 'लागत मूल्य',
    'dealer.minQty': 'न्यूनतम मात्रा',
    'dealer.validTill': 'वैधता तारीख',
    'dealer.gstPercent': 'जीएसटी %',
    'dealer.quotationPrefix': 'कोटेशन — IT सॉल्यूशंस',
    'dealer.quotationClient': 'ग्राहक',
    'dealer.quotationDate': 'दिनांक',

    // Calculator return values
    'Hardware (Year 0)': 'हार्डवेयर (वर्ष 0)',
    'Annual operating cost': 'वार्षिक परिचालन लागत',
    '{years}-Year TCO': '{years}-वर्ष TCO',
    'Margin %': 'मार्जिन %',
    'Margin ₹': 'मार्जिन ₹',
    'MRP': 'बिक्री मूल्य (MRP)',
    'Cost': 'लागत मूल्य',

    // Schemes Board
    'HP Spring Surge Q2 2025': 'एचपी स्प्रिंग सर्ज Q२ २०२५',
    'ProLiant Servers': 'प्रोलायंट सर्वर',
    'ThinkPad Business Booster': 'थिंकपैड बिजनेस बूस्टर',
    'ThinkPad Series': 'थिंकपैड सीरीज',
    'PowerEdge Partner Promo': 'पॉवरएज पार्टनर प्रोमो',
    'PowerEdge + iDRAC': 'पॉवरएज + iDRAC',
    'Smart Net Total Care Bundle': 'स्मार्ट नेट Total Care बंडल',
    'Cisco Switches': 'सिस्को स्विचेस',
    'Print More Save More': 'प्रिंट मोर सेव मोर',
    'EcoTank Series': 'इकोटैंक सीरीज',
    '₹5,000 cashback/unit': '₹५,००० कैशबैक/यूनिट',
    '15% off AMC': 'एएमसी पर १५% छूट',
    '₹2,000 bundle saving': '₹२,००० बंडल बचत',
    'Volume': 'वॉल्यूम',
    'Target': 'टारगेट',
    'Bundle': 'बंडल',
    'Service': 'सेवा',
    'Ink+Hardware': 'इंक+हार्डवेयर',
    'HOT': 'हॉट',
    'NEW': 'नया',
    'LIMITED': 'सीमित',

    // Enterprise
    'enterprise.infra': 'इन्फ्रा प्लानर',
    'enterprise.tco': 'TCO कैलकुलेटर',
    'enterprise.lifecycle': 'जीवनचक्र प्रबंधक',
    'enterprise.compliance': 'अनुपालन',
    'enterprise.tcoInputs': '⚙️ TCO इनपुट',
    'enterprise.hardwareCost': 'हार्डवेअर लागत (₹)',
    'enterprise.maintenanceCost': 'वार्षिक रखरखाव (₹)',
    'enterprise.licenseCost': 'वार्षिक लाइसेंस (₹)',
    'enterprise.powerCost': 'वार्षिक बिजली लागत (₹)',
    'enterprise.period': 'विश्लेषण अवधि (वर्ष)',
    'enterprise.tcoSummary': '📊 TCO सारांश',
    'enterprise.yearCumulative': 'वर्ष-दर-वर्ष संचयी',
    'enterprise.year': 'वर्ष',
    'enterprise.customInfraTitle': '🔧 कस्टम इन्फ्रा अनुरोध',
    'enterprise.customInfraPlaceholder': 'अपनी इन्फ्रास्ट्रक्चर आवश्यकताओं का वर्णन करें...',
    'enterprise.planBtn': 'योजना →',
    'enterprise.planningProgress': 'आपकी इन्फ्रास्ट्रक्चर योजना डिज़ाइन की जा रही है...',
    'enterprise.smbOffice': 'SMB ऑफिस (२५ उपयोगकर्ता)',
    'enterprise.smbOfficeDesc': 'छोटे व्यवसाय के लिए पूर्ण स्नातक',
    'enterprise.entOffice': 'एंटरप्राइज (२०० उपयोगकर्ता)',
    'enterprise.entOfficeDesc': 'पूर्ण डेटा सेंटर + एंड-यूज़र कंप्यूट',
    'enterprise.hospital': 'अस्पताल / स्वास्थ्य सेवा',
    'enterprise.hospitalDesc': 'HIPAA-अनुपालन सेटअप',
    'enterprise.school': 'स्कूल / शिक्षा',
    'enterprise.schoolDesc': 'किफायती शिक्षण वातावरण',

    // Market
    'market.demand': 'मांग सूचकांक',
    'market.price': 'मूल्य रुझान',
    'market.forecast': 'पूर्वानुमान',
    'market.brands': 'ब्रांड हिस्सेदारी',
    'market.disclaimer': '⚠️ पूर्वानुमान AI अनुमान हैं — गारंटी नहीं',
    'market.loading': 'बाज़ार चार्ट और विश्लेषण लोड हो रहा है...',
    'market.demandIndexTitle': 'मांग सूचकांक (पिछले ६ महीने)',
    'market.priceTrendTitle': 'मूल्य रुझान (इतिहास + डॉटेड AI पूर्वानुमान)',
    'market.brandShareTitle': 'ब्रांड बाजार हिस्सेदारी (क्षेत्रीय वितरण)',
    'market.seasonalPatternTitle': 'मौसमी मांग पैटर्न',
    'market.peakWindowTag': 'अगला पीक सीजनल विंडो',
    'market.peakWindowDesc': 'जुलाई - अगस्त: उच्च शिक्षा प्रवेश रिफ्रेश साइकिल',
    'market.forecastTitle': 'AI बाज़ार बुद्धिमत्ता पूर्वानुमान (अगले ९० दिन)',
    'market.disclaimerTag': 'अस्वीकरण',
    'market.chart.history': 'इतिहास',
    'market.chart.forecast': 'AI पूर्वानुमान',
    'market.chart.prev': 'पिछला',
    'market.chart.current': 'वर्तमान',
    'market.month.Jan': 'जन',
    'market.month.Feb': 'फर',
    'market.month.Mar': 'मार्च',
    'market.month.Apr': 'अप्रैल',
    'market.month.May': 'मई',
    'market.month.Jun': 'जून',

    // News
    'news.allNews': 'सभी समाचार',
    'news.globalIt': 'वैश्विक IT',
    'news.indiaIt': 'भारतीय IT',
    'news.brandNews': 'ब्रांड समाचार',
    'news.launches': 'लॉन्चिंग',
    'news.aiHardware': 'AI हार्डवेयर',
    'news.semiconductors': 'सेमीकंडक्टर',
    'news.supplyChain': 'सप्लाई चेन',
    'news.trends': 'ट्रेंड्स',
    'news.govtPolicy': 'सरकारी नीति',
    'news.searchPlaceholder': 'समाचार खोजें...',
    'news.loading': 'IT समाचार लोड हो रहे हैं...',
    'news.noNews': 'इस श्रेणी में आपकी खोज से मेल खाता कोई समाचार नहीं मिला.',
    'news.businessImpactTitle': '💼 व्यावसायिक प्रभाव (डीलर)',
    'news.technicalImpactTitle': '⚙️ तकनीकी प्रभाव (स्पेसिफिकेशन्स)',
    'news.relatedProducts': 'संबंधित उत्पाद: ',
    'news.readLess': 'कम पढ़ें ▲',
    'news.readMore': 'व्यावसायिक प्रभाव विश्लेषण ▼',
    'news.askAi': 'AI सहायक से पूछें 🤖',

    // Learn
    'learn.certificationsEarned': 'अर्जित प्रमाणपत्र:',
    'learn.knowledgeModules': 'ज्ञान मॉड्यूल',
    'learn.topic': 'मॉड्यूल विषय:',
    'learn.readLesson': 'पाठ पढ़ें',
    'learn.takeQuiz': 'क्विज़ लें',
    'learn.readyText': 'ज्ञान का परीक्षण करने के लिए तैयार हैं?',
    'learn.readyDesc': '५ प्रश्नों की क्विज़ पूरी करें. प्रमाणपत्र बैज अर्जित करने के लिए ८०% (४ सही उत्तर) अंक प्राप्त करें.',
    'learn.startQuiz': 'इंटरएक्टिव क्विज़ शुरू करें ✍️',
    'learn.submitAnswers': 'उत्तर सबमिट करें',
    'learn.certEarned': '🏆 प्रमाणपत्र प्राप्त हुआ!',
    'learn.tryAgain': '😢 पुनः प्रयास करें',
    'learn.scoreText': 'आपने {score}% स्कोर किया ({correct} / {total} सही उत्तर).',
    'learn.retakeQuiz': 'क्विज़ पुनः लें',
    'learn.selectModule': 'सीखना शुरू करने के लिए मॉड्यूल चुनें',
    'learn.selectModuleDesc': 'ट्यूटोरियल देखने, कौशल का परीक्षण करने और आधिकारिक प्रमाणपत्र प्राप्त करने के लिए बाईं ओर सूची से चयन करें.',
    'learn.explanation': 'स्पष्टीकरण:',

    // Solutions
    'solutions.selectUseCase': '१. उपयोग का प्रकार चुनें',
    'solutions.scaleBudget': '२. स्केल और बजट',
    'solutions.priorities': '३. प्राथमिकताएं',
    'solutions.userCount': 'उपयोगकर्ताओं की संख्या',
    'solutions.budgedRange': 'बजट सीमा',
    'solutions.designBtn': '⚡ मेरा सॉल्यूशन डिज़ाइन करें',
    'solutions.designProgress': '⚡ सॉल्यूशन डिज़ाइन किया जा रहा है...',
    'solutions.configureGenerate': 'कॉन्फ़िगर और जनरेट',
    'solutions.configureGenerateDesc': 'उपयोग का प्रकार चुनें, स्केल और बजट सेट करें और अनुशंसाओं के लिए "मेरा सॉल्यूशन डिज़ाइन करें" पर क्लिक करें.',
    'solutions.designingMessage': 'आपका कस्टम IT सॉल्यूशन डिज़ाइन किया जा रहा है...',
    'solutions.customPlaceholder': 'या कस्टम उपयोग का वर्णन करें...',
    'solutions.titleOutput': 'सॉल्यूशन डिज़ाइन',
    'solutions.copyBtn': '📋 कॉपी',

    // Budget ranges
    'Under ₹2 Lakh': '₹2 लाख से कम',
    '₹2–5 Lakh': '₹2–5 लाख',
    '₹5–15 Lakh': '₹5–15 लाख',
    '₹15–50 Lakh': '₹15–50 लाख',
    'Above ₹50 Lakh': '₹50 लाख से अधिक',

    // Use cases & priority
    'solutions.usecase.office': 'ऑफिस सेटअप',
    'solutions.usecase.video': 'वीडियो प्रोडक्शन',
    'solutions.usecase.retail': 'रिटेल/POS सेटअप',
    'solutions.usecase.datacenter': 'मिनी डेटा सेंटर',
    'solutions.usecase.creative': 'क्रिएटिव एजेंसी',
    'solutions.usecase.hospital': 'क्लिनिक / अस्पताल',
    'solutions.usecase.school': 'स्कूल लैब',
    'solutions.usecase.warehouse': 'वेयरहाउस / लॉजिस्टिक्स',
    'solutions.priority.performance': 'उत्कृष्ट प्रदर्शन',
    'solutions.priority.cost': 'किफायती',
    'solutions.priority.energy': 'ऊर्जा कुशल',
    'solutions.priority.scalable': 'स्केलेबल',
    'solutions.priority.manage': 'प्रबंधन में आसान',
    'solutions.priority.availability': 'उच्च उपलब्धता',

    // Language names
    'lang.en': 'EN',
    'lang.mr': 'मर',
    'lang.hi': 'हि',
  }
};

export function t(key, lang = 'en') {
  return translations[lang]?.[key] || translations['en']?.[key] || key;
}

export function detectLang(text = '') {
  const deva = (text.match(/[\u0900-\u097F]/g) || []).length;
  if (deva < 2) return 'en';
  const mr = ['आहे', 'आहेत', 'नाही', 'करा', 'सांगा', 'मला', 'तुम्ही', 'काय', 'कसा'].filter(w => text.includes(w)).length;
  const hi = ['है', 'हैं', 'नहीं', 'करो', 'बताओ', 'मुझे', 'आप', 'क्या', 'कैसा'].filter(w => text.includes(w)).length;
  return mr >= hi ? 'mr' : 'hi';
}

export default { t, detectLang };
