const translations = {
  en: {
    // Navigation
    'nav.chat': 'AI Chat',
    'nav.sales': 'Sales Coach',
    'nav.dealer': 'Dealer',
    'nav.enterprise': 'Enterprise',
    'nav.solutions': 'Solutions',
    'nav.news': 'News',
    'nav.learn': 'Learn',
    'nav.market': 'Market',
    // Common
    'common.search': 'Search...',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.retry': 'Retry',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.save': 'Save',
    'common.export': 'Export',
    'common.copy': 'Copy',
    'common.new': 'New',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    // Chat
    'chat.placeholder': 'Ask about products, ROI, compatibility, solutions...',
    'chat.send': 'Send',
    'chat.newChat': 'New Chat',
    'chat.history': 'Chat History',
    'chat.agent': 'Agent',
    'chat.selectAgent': 'Select Agent',
    'chat.thinking': 'Thinking...',
    'chat.source': 'Source',
    'chat.confidence': 'Confidence',
    'chat.copy': 'Copy response',
    'chat.micEn': '🎤 EN',
    'chat.micMr': '🎤 मर',
    'chat.micHi': '🎤 हि',
    // Modules
    'module.chat.title': 'AI Chat — Agent Playground',
    'module.chat.desc': 'Chat with 14 specialized AI agents',
    'module.sales.title': 'Sales Coach Portal',
    'module.sales.desc': 'Playbooks, pitch generator, objection handler',
    'module.dealer.title': 'Dealer Portal',
    'module.dealer.desc': 'Quotations, stock, schemes, margins',
    'module.enterprise.title': 'Enterprise Portal',
    'module.enterprise.desc': 'Infra planning, TCO, lifecycle management',
    'module.solutions.title': 'Solution Designer',
    'module.solutions.desc': 'Design complete IT setups for any use-case',
    'module.news.title': 'IT News Center',
    'module.news.desc': 'Global and India IT news with AI summaries',
    'module.learn.title': 'Learning Center',
    'module.learn.desc': 'Hardware courses, quizzes, certifications',
    'module.market.title': 'Market Intelligence',
    'module.market.desc': 'Demand trends, price forecasts, brand analytics',
    // Sales Coach
    'sales.playbooks': 'Playbooks',
    'sales.pitch': 'Pitch Generator',
    'sales.objection': 'Objection Handler',
    'sales.negotiation': 'Negotiation Coach',
    'sales.discovery': 'Discovery Questions',
    // Dealer
    'dealer.quotation': 'Quotation Creator',
    'dealer.stock': 'Stock Checker',
    'dealer.schemes': 'Scheme Board',
    'dealer.bulk': 'Bulk Planner',
    'dealer.margin': 'Margin Calculator',
    // Enterprise
    'enterprise.infra': 'Infrastructure Planner',
    'enterprise.tco': 'TCO Calculator',
    'enterprise.lifecycle': 'Lifecycle Manager',
    'enterprise.compliance': 'Compliance',
    // Market
    'market.demand': 'Demand Index',
    'market.price': 'Price Trends',
    'market.forecast': 'Forecasts',
    'market.brands': 'Brand Share',
    'market.disclaimer': '⚠️ Forecasts are AI estimates — not guaranteed',
    // Language names
    'lang.en': 'EN',
    'lang.mr': 'मर',
    'lang.hi': 'हि',

    // Dealer Quotation & Margin
    'dealer.customerNamePlaceholder': 'Customer / Company name',
    'dealer.productNamePlaceholder': 'Product name',
    'dealer.productHeader': 'Product',
    'dealer.skuHeader': 'SKU',
    'dealer.qtyHeader': 'Qty',
    'dealer.priceHeader': 'Unit Price',
    'dealer.totalHeader': 'Total',
    'dealer.subtotalLabel': 'Subtotal',
    'dealer.gstLabel': 'GST',
    'dealer.grandTotalLabel': 'Grand Total',
    'dealer.copied': '✅ Copied!',
    'dealer.copyQuotation': '📋 Copy Quotation',
    'dealer.addLineItem': '+ Add Line Item',
    'dealer.exportPdf': 'Export PDF',
    'dealer.marginCalculatorTitle': 'Margin Calculator',
    'dealer.sellingPriceLabel': 'Selling Price (MRP)',
    'dealer.costPriceLabel': 'Cost Price',
    'dealer.minQty': 'Min qty',
    'dealer.validTill': 'Valid till',

    // Schemes Board
    'HP Spring Surge Q2 2025': 'HP Spring Surge Q2 2025',
    'ProLiant Servers': 'ProLiant Servers',
    'ThinkPad Business Booster': 'ThinkPad Business Booster',
    'ThinkPad Series': 'ThinkPad Series',
    'PowerEdge Partner Promo': 'PowerEdge Partner Promo',
    'PowerEdge + iDRAC': 'PowerEdge + iDRAC',
    'Smart Net Total Care Bundle': 'Smart Net Total Care Bundle',
    'Cisco Switches': 'Cisco Switches',
    'Print More Save More': 'Print More Save More',
    'EcoTank Series': 'EcoTank Series',
    '₹5,000 cashback/unit': '₹5,000 cashback/unit',
    '15% off AMC': '15% off AMC',
    '₹2,000 bundle saving': '₹2,000 bundle saving',
    'Volume': 'Volume',
    'Target': 'Target',
    'Bundle': 'Bundle',
    'Service': 'Service',
    'Ink+Hardware': 'Ink+Hardware',
  },
  mr: {
    // Navigation
    'nav.chat': 'AI चॅट',
    'nav.sales': 'सेल्स कोच',
    'nav.dealer': 'डीलर',
    'nav.enterprise': 'एंटरप्राइज',
    'nav.solutions': 'सोल्युशन',
    'nav.news': 'बातम्या',
    'nav.learn': 'शिका',
    'nav.market': 'बाजार',
    // Common
    'common.search': 'शोधा...',
    'common.loading': 'लोड होत आहे...',
    'common.error': 'त्रुटी',
    'common.retry': 'पुन्हा प्रयत्न करा',
    'common.close': 'बंद करा',
    'common.back': 'मागे',
    'common.save': 'जतन करा',
    'common.export': 'निर्यात',
    'common.copy': 'कॉपी करा',
    'common.new': 'नवीन',
    'common.delete': 'हटवा',
    'common.edit': 'संपादन',
    'common.view': 'पाहा',
    'common.submit': 'सादर करा',
    'common.cancel': 'रद्द करा',
    // Chat
    'chat.placeholder': 'उत्पादने, ROI, सुसंगतता, सोल्युशन विचारा...',
    'chat.send': 'पाठवा',
    'chat.newChat': 'नवीन चॅट',
    'chat.history': 'चॅट इतिहास',
    'chat.agent': 'एजंट',
    'chat.selectAgent': 'एजंट निवडा',
    'chat.thinking': 'विचार करत आहे...',
    'chat.source': 'स्रोत',
    'chat.confidence': 'विश्वास',
    'chat.copy': 'प्रतिसाद कॉपी करा',
    'chat.micEn': '🎤 EN',
    'chat.micMr': '🎤 मर',
    'chat.micHi': '🎤 हि',
    // Modules
    'module.chat.title': 'AI चॅट — एजंट प्लेग्राउंड',
    'module.chat.desc': '१४ विशेष AI एजंटशी चॅट करा',
    'module.sales.title': 'सेल्स कोच पोर्टल',
    'module.sales.desc': 'प्लेबुक, पिच जनरेटर, आक्षेप हँडलर',
    'module.dealer.title': 'डीलर पोर्टल',
    'module.dealer.desc': 'कोटेशन, स्टॉक, योजना, मार्जिन',
    'module.enterprise.title': 'एंटरप्राइज पोर्टल',
    'module.enterprise.desc': 'इन्फ्रा नियोजन, TCO, जीवनचक्र',
    'module.solutions.title': 'सोल्युशन डिझायनर',
    'module.solutions.desc': 'कोणत्याही वापरासाठी IT सेटअप डिझाइन करा',
    'module.news.title': 'IT बातम्या केंद्र',
    'module.news.desc': 'जागतिक आणि भारतीय IT बातम्या AI सारांशासह',
    'module.learn.title': 'शिक्षण केंद्र',
    'module.learn.desc': 'हार्डवेअर अभ्यासक्रम, प्रश्नमंजुषा, प्रमाणपत्रे',
    'module.market.title': 'बाजार बुद्धिमत्ता',
    'module.market.desc': 'मागणी ट्रेंड, किंमत अंदाज, ब्रँड विश्लेषण',
    // Sales Coach
    'sales.playbooks': 'प्लेबुक',
    'sales.pitch': 'पिच जनरेटर',
    'sales.objection': 'आक्षेप हँडलर',
    'sales.negotiation': 'वाटाघाट कोच',
    'sales.discovery': 'शोध प्रश्न',
    // Dealer
    'dealer.quotation': 'कोटेशन',
    'dealer.stock': 'स्टॉक तपासा',
    'dealer.schemes': 'योजना बोर्ड',
    'dealer.bulk': 'बल्क प्लानर',
    'dealer.margin': 'मार्जिन कॅल्क्युलेटर',
    // Enterprise
    'enterprise.infra': 'इन्फ्रा नियोजक',
    'enterprise.tco': 'TCO कॅल्क्युलेटर',
    'enterprise.lifecycle': 'जीवनचक्र व्यवस्थापक',
    'enterprise.compliance': 'अनुपालन',
    // Market
    'market.demand': 'मागणी निर्देशांक',
    'market.price': 'किंमत ट्रेंड',
    'market.forecast': 'अंदाज',
    'market.brands': 'ब्रँड हिस्सा',
    'market.disclaimer': '⚠️ अंदाज AI अनुमान आहेत — हमी नाही',
    // Language names
    'lang.en': 'EN',
    'lang.mr': 'मर',
    'lang.hi': 'हि',
    // Common fallbacks
    'common.export': 'निर्यात',
    'common.copy': 'कॉपी करा',

    // Dealer Quotation & Margin
    'dealer.customerNamePlaceholder': 'ग्राहक / कंपनीचे नाव',
    'dealer.productNamePlaceholder': 'उत्पादनाचे नाव',
    'dealer.productHeader': 'उत्पादन',
    'dealer.skuHeader': 'SKU',
    'dealer.qtyHeader': 'प्रमाण',
    'dealer.priceHeader': 'दर',
    'dealer.totalHeader': 'एकूण',
    'dealer.subtotalLabel': 'उपएकूण',
    'dealer.gstLabel': 'जीएसटी',
    'dealer.grandTotalLabel': 'एकूण देय रक्कम',
    'dealer.copied': '✅ कॉपी केले!',
    'dealer.copyQuotation': '📋 कोटेशन कॉपी करा',
    'dealer.addLineItem': '+ नवीन ओळ जोडा',
    'dealer.exportPdf': 'पीडीएफ डाउनलोड करा',
    'dealer.marginCalculatorTitle': 'मार्जिन कॅल्क्युलेटर',
    'dealer.sellingPriceLabel': 'विक्री किंमत (MRP)',
    'dealer.costPriceLabel': 'खरेदी किंमत',
    'dealer.minQty': 'किमान प्रमाण',
    'dealer.validTill': 'वैधता तारीख',

    // Schemes Board
    'HP Spring Surge Q2 2025': 'एचपी स्प्रिंग सर्ज Q२ २०२५',
    'ProLiant Servers': 'प्रोलायंट सर्व्हर्स',
    'ThinkPad Business Booster': 'थिंकपॅड बिझनेस बूस्टर',
    'ThinkPad Series': 'थिंकपॅड सिरीज',
    'PowerEdge Partner Promo': 'पॉवरएज पार्टनर प्रोमो',
    'PowerEdge + iDRAC': 'पॉवरएज + iDRAC',
    'Smart Net Total Care Bundle': 'स्मार्ट नेट टोटल केअर बंडल',
    'Cisco Switches': 'सिस्को स्विचेस',
    'Print More Save More': 'प्रिंट मोअर सेव्ह मोअर',
    'EcoTank Series': 'इकोटँक सिरीज',
    '₹5,000 cashback/unit': '₹५,००० कॅशबॅक/युनिट',
    '15% off AMC': 'एएमसी वर १५% सूट',
    '₹2,000 bundle saving': '₹२,००० बंडल बचत',
    'Volume': 'व्हॉल्यूम',
    'Target': 'टार्गेट',
    'Bundle': 'बंडल',
    'Service': 'सेवा',
    'Ink+Hardware': 'इंक+हार्डवेअर',
  },
  hi: {
    // Navigation
    'nav.chat': 'AI चैट',
    'nav.sales': 'सेल्स कोच',
    'nav.dealer': 'डीलर',
    'nav.enterprise': 'एंटरप्राइज',
    'nav.solutions': 'सॉल्यूशन',
    'nav.news': 'समाचार',
    'nav.learn': 'सीखें',
    'nav.market': 'बाज़ार',
    // Common
    'common.search': 'खोजें...',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.retry': 'पुनः प्रयास',
    'common.close': 'बंद करें',
    'common.back': 'वापस',
    'common.save': 'सहेजें',
    'common.export': 'निर्यात',
    'common.copy': 'कॉपी करें',
    'common.new': 'नया',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित',
    'common.view': 'देखें',
    'common.submit': 'सबमिट',
    'common.cancel': 'रद्द करें',
    // Chat
    'chat.placeholder': 'उत्पाद, ROI, संगतता, सॉल्यूशन पूछें...',
    'chat.send': 'भेजें',
    'chat.newChat': 'नई चैट',
    'chat.history': 'चैट इतिहास',
    'chat.agent': 'एजेंट',
    'chat.selectAgent': 'एजेंट चुनें',
    'chat.thinking': 'सोच रहा है...',
    'chat.source': 'स्रोत',
    'chat.confidence': 'विश्वास',
    'chat.copy': 'उत्तर कॉपी करें',
    'chat.micEn': '🎤 EN',
    'chat.micMr': '🎤 मर',
    'chat.micHi': '🎤 हि',
    // Modules
    'module.chat.title': 'AI चैट — एजेंट प्लेग्राउंड',
    'module.chat.desc': '14 विशेष AI एजेंटों से चैट करें',
    'module.sales.title': 'सेल्स कोच पोर्टल',
    'module.sales.desc': 'प्लेबुक, पिच जेनरेटर, आपत्ति हैंडलर',
    'module.dealer.title': 'डीलर पोर्टल',
    'module.dealer.desc': 'कोटेशन, स्टॉक, स्कीम, मार्जिन',
    'module.enterprise.title': 'एंटरप्राइज पोर्टल',
    'module.enterprise.desc': 'इन्फ्रा नियोजन, TCO, जीवनचक्र प्रबंधन',
    'module.solutions.title': 'सॉल्यूशन डिज़ाइनर',
    'module.solutions.desc': 'किसी भी उपयोग के लिए IT सेटअप डिज़ाइन करें',
    'module.news.title': 'IT समाचार केंद्र',
    'module.news.desc': 'वैश्विक और भारतीय IT समाचार AI सारांश के साथ',
    'module.learn.title': 'सीखने का केंद्र',
    'module.learn.desc': 'हार्डवेयर कोर्स, क्विज़, प्रमाणपत्र',
    'module.market.title': 'बाज़ार बुद्धिमत्ता',
    'module.market.desc': 'मांग रुझान, मूल्य पूर्वानुमान, ब्रांड विश्लेषण',
    // Sales Coach
    'sales.playbooks': 'प्लेबुक',
    'sales.pitch': 'पिच जेनरेटर',
    'sales.objection': 'आपत्ति हैंडलर',
    'sales.negotiation': 'बातचीत कोच',
    'sales.discovery': 'डिस्कवरी प्रश्न',
    // Dealer
    'dealer.quotation': 'कोटेशन',
    'dealer.stock': 'स्टॉक जांचें',
    'dealer.schemes': 'स्कीम बोर्ड',
    'dealer.bulk': 'बल्क प्लानर',
    'dealer.margin': 'मार्जिन कैलकुलेटर',
    // Enterprise
    'enterprise.infra': 'इन्फ्रा प्लानर',
    'enterprise.tco': 'TCO कैलकुलेटर',
    'enterprise.lifecycle': 'जीवनचक्र प्रबंधक',
    'enterprise.compliance': 'अनुपालन',
    // Market
    'market.demand': 'मांग सूचकांक',
    'market.price': 'मूल्य रुझान',
    'market.forecast': 'पूर्वानुमान',
    'market.brands': 'ब्रांड हिस्सेदारी',
    'market.disclaimer': '⚠️ पूर्वानुमान AI अनुमान हैं — गारंटी नहीं',
    // Language names
    'lang.en': 'EN',
    'lang.mr': 'मर',
    'lang.hi': 'हि',

    // Dealer Quotation & Margin
    'dealer.customerNamePlaceholder': 'ग्राहक / कंपनी का नाम',
    'dealer.productNamePlaceholder': 'उत्पाद का नाम',
    'dealer.productHeader': 'उत्पाद',
    'dealer.skuHeader': 'SKU',
    'dealer.qtyHeader': 'मात्रा',
    'dealer.priceHeader': 'दर',
    'dealer.totalHeader': 'कुल',
    'dealer.subtotalLabel': 'उप-योग',
    'dealer.gstLabel': 'जीएसटी',
    'dealer.grandTotalLabel': 'कुल देय राशि',
    'dealer.copied': '✅ कॉपी हो गया!',
    'dealer.copyQuotation': '📋 कोटेशन कॉपी करें',
    'dealer.addLineItem': '+ नई पंक्ति जोड़ें',
    'dealer.exportPdf': 'पीडीएफ निर्यात करें',
    'dealer.marginCalculatorTitle': 'मार्जिन कैलकुलेटर',
    'dealer.sellingPriceLabel': 'बिक्री मूल्य (MRP)',
    'dealer.costPriceLabel': 'लागत मूल्य',
    'dealer.minQty': 'न्यूनतम मात्रा',
    'dealer.validTill': 'वैधता तारीख',

    // Schemes Board
    'HP Spring Surge Q2 2025': 'एचपी स्प्रिंग सर्ज Q२ २०२५',
    'ProLiant Servers': 'प्रोलायंट सर्वर',
    'ThinkPad Business Booster': 'थिंकपैड बिजनेस बूस्टर',
    'ThinkPad Series': 'थिंकपैड सीरीज',
    'PowerEdge Partner Promo': 'पॉवरएज पार्टनर प्रोमो',
    'PowerEdge + iDRAC': 'पॉवरएज + iDRAC',
    'Smart Net Total Care Bundle': 'स्मार्ट नेट टोटल केयर बंडल',
    'Cisco Switches': 'सिस्को स्विचेस',
    'Print More Save More': 'प्रिंट मोर सेव मोर',
    'EcoTank Series': 'इकोटैंक सीरीज',
    '₹5,000 cashback/unit': '₹५,००० कैशबैक/यूनिट',
    '15% off AMC': 'एएमसी पर १५% छूट',
    '₹2,000 bundle saving': '₹२,००० बंडल बचत',
    'Volume': 'वॉल्यूम',
    'Target': 'टारगेट',
    'Bundle': 'बंडल',
    'Service': 'सेवा',
    'Ink+Hardware': 'इंक+हार्डवेयर',
  }
};

export function t(key, lang = 'en') {
  return translations[lang]?.[key] || translations['en']?.[key] || key;
}

export function detectLang(text = '') {
  const deva = (text.match(/[\u0900-\u097F]/g) || []).length;
  if (deva < 2) return 'en';
  const mr = ['आहे', 'आहेत', 'नाही', 'करा', 'सांगा', 'मला', 'तुम्ही', 'काय', 'कसा'].filter(w => text.includes(w)).length;
  const hi = ['है', 'हैं', 'नहीं', 'करो', 'बताओ', 'मुझे', 'आप', 'क्या', 'कैसा'].filter(w => text.includes(w)).length;
  return mr >= hi ? 'mr' : 'hi';
}

export default { t, detectLang };
